/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file VrDoctorDone.cs instead.
*/
#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Runtime.Serialization;
using System.Xml.Serialization;
#endregion

namespace ePrescription.Entities
{
	///<summary>
	/// An object representation of the 'Vr_DoctorDone' view. [No description found in the database]	
	///</summary>
	[Serializable]
	[CLSCompliant(true)]
	[ToolboxItem("VrDoctorDoneBase")]
	public abstract partial class VrDoctorDoneBase : System.IComparable, System.ICloneable, INotifyPropertyChanged
	{
		
		#region Variable Declarations
		
		/// <summary>
		/// StatId : 
		/// </summary>
		private System.Int64		  _statId = (long)0;
		
		/// <summary>
		/// PatientCode : 
		/// </summary>
		private System.String		  _patientCode = string.Empty;
		
		/// <summary>
		/// TID : 
		/// </summary>
		private System.String		  _tid = string.Empty;
		
		/// <summary>
		/// FirstName : 
		/// </summary>
		private System.String		  _firstName = string.Empty;
		
		/// <summary>
		/// LastName : 
		/// </summary>
		private System.String		  _lastName = string.Empty;
		
		/// <summary>
		/// DOB : 
		/// </summary>
		private System.DateTime		  _dob = DateTime.MinValue;
		
		/// <summary>
		/// Sex : 
		/// </summary>
		private System.String		  _sex = string.Empty;
		
		/// <summary>
		/// Nationality : 
		/// </summary>
		private System.String		  _nationality = string.Empty;
		
		/// <summary>
		/// PatientStart : 
		/// </summary>
		private System.Boolean?		  _patientStart = null;
		
		/// <summary>
		/// VitalSign : 
		/// </summary>
		private System.String		  _vitalSign = null;
		
		/// <summary>
		/// Lab : 
		/// </summary>
		private System.String		  _lab = null;
		
		/// <summary>
		/// Xray : 
		/// </summary>
		private System.String		  _xray = null;
		
		/// <summary>
		/// UltraSound : 
		/// </summary>
		private System.String		  _ultraSound = null;
		
		/// <summary>
		/// Cardiology : 
		/// </summary>
		private System.String		  _cardiology = null;
		
		/// <summary>
		/// MedReport : 
		/// </summary>
		private System.String		  _medReport = null;
		
		/// <summary>
		/// ChargedCodes : 
		/// </summary>
		private System.String		  _chargedCodes = null;
		
		/// <summary>
		/// IsCompleted : 
		/// </summary>
		private System.Boolean?		  _isCompleted = null;
		
		/// <summary>
		/// CreateDate : 
		/// </summary>
		private System.DateTime?		  _createDate = null;
		
		/// <summary>
		/// Object that contains data to associate with this object
		/// </summary>
		private object _tag;
		
		/// <summary>
		/// Suppresses Entity Events from Firing, 
		/// useful when loading the entities from the database.
		/// </summary>
	    [NonSerialized] 
		private bool suppressEntityEvents = false;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="VrDoctorDoneBase"/> instance.
		///</summary>
		public VrDoctorDoneBase()
		{
		}		
		
		///<summary>
		/// Creates a new <see cref="VrDoctorDoneBase"/> instance.
		///</summary>
		///<param name="_statId"></param>
		///<param name="_patientCode"></param>
		///<param name="_tid"></param>
		///<param name="_firstName"></param>
		///<param name="_lastName"></param>
		///<param name="_dob"></param>
		///<param name="_sex"></param>
		///<param name="_nationality"></param>
		///<param name="_patientStart"></param>
		///<param name="_vitalSign"></param>
		///<param name="_lab"></param>
		///<param name="_xray"></param>
		///<param name="_ultraSound"></param>
		///<param name="_cardiology"></param>
		///<param name="_medReport"></param>
		///<param name="_chargedCodes"></param>
		///<param name="_isCompleted"></param>
		///<param name="_createDate"></param>
		public VrDoctorDoneBase(System.Int64 _statId, System.String _patientCode, System.String _tid, System.String _firstName, System.String _lastName, System.DateTime _dob, System.String _sex, System.String _nationality, System.Boolean? _patientStart, System.String _vitalSign, System.String _lab, System.String _xray, System.String _ultraSound, System.String _cardiology, System.String _medReport, System.String _chargedCodes, System.Boolean? _isCompleted, System.DateTime? _createDate)
		{
			this._statId = _statId;
			this._patientCode = _patientCode;
			this._tid = _tid;
			this._firstName = _firstName;
			this._lastName = _lastName;
			this._dob = _dob;
			this._sex = _sex;
			this._nationality = _nationality;
			this._patientStart = _patientStart;
			this._vitalSign = _vitalSign;
			this._lab = _lab;
			this._xray = _xray;
			this._ultraSound = _ultraSound;
			this._cardiology = _cardiology;
			this._medReport = _medReport;
			this._chargedCodes = _chargedCodes;
			this._isCompleted = _isCompleted;
			this._createDate = _createDate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="VrDoctorDone"/> instance.
		///</summary>
		///<param name="_statId"></param>
		///<param name="_patientCode"></param>
		///<param name="_tid"></param>
		///<param name="_firstName"></param>
		///<param name="_lastName"></param>
		///<param name="_dob"></param>
		///<param name="_sex"></param>
		///<param name="_nationality"></param>
		///<param name="_patientStart"></param>
		///<param name="_vitalSign"></param>
		///<param name="_lab"></param>
		///<param name="_xray"></param>
		///<param name="_ultraSound"></param>
		///<param name="_cardiology"></param>
		///<param name="_medReport"></param>
		///<param name="_chargedCodes"></param>
		///<param name="_isCompleted"></param>
		///<param name="_createDate"></param>
		public static VrDoctorDone CreateVrDoctorDone(System.Int64 _statId, System.String _patientCode, System.String _tid, System.String _firstName, System.String _lastName, System.DateTime _dob, System.String _sex, System.String _nationality, System.Boolean? _patientStart, System.String _vitalSign, System.String _lab, System.String _xray, System.String _ultraSound, System.String _cardiology, System.String _medReport, System.String _chargedCodes, System.Boolean? _isCompleted, System.DateTime? _createDate)
		{
			VrDoctorDone newVrDoctorDone = new VrDoctorDone();
			newVrDoctorDone.StatId = _statId;
			newVrDoctorDone.PatientCode = _patientCode;
			newVrDoctorDone.Tid = _tid;
			newVrDoctorDone.FirstName = _firstName;
			newVrDoctorDone.LastName = _lastName;
			newVrDoctorDone.Dob = _dob;
			newVrDoctorDone.Sex = _sex;
			newVrDoctorDone.Nationality = _nationality;
			newVrDoctorDone.PatientStart = _patientStart;
			newVrDoctorDone.VitalSign = _vitalSign;
			newVrDoctorDone.Lab = _lab;
			newVrDoctorDone.Xray = _xray;
			newVrDoctorDone.UltraSound = _ultraSound;
			newVrDoctorDone.Cardiology = _cardiology;
			newVrDoctorDone.MedReport = _medReport;
			newVrDoctorDone.ChargedCodes = _chargedCodes;
			newVrDoctorDone.IsCompleted = _isCompleted;
			newVrDoctorDone.CreateDate = _createDate;
			return newVrDoctorDone;
		}
				
		#endregion Constructors
		
		#region Properties	
		/// <summary>
		/// 	Gets or Sets the StatId property. 
		///		
		/// </summary>
		/// <value>This type is bigint</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int64 StatId
		{
			get
			{
				return this._statId; 
			}
			set
			{
				if (_statId == value)
					return;
					
				this._statId = value;
				this._isDirty = true;
				
				OnPropertyChanged("StatId");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the PatientCode property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String PatientCode
		{
			get
			{
				return this._patientCode; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "PatientCode does not allow null values.");
				if (_patientCode == value)
					return;
					
				this._patientCode = value;
				this._isDirty = true;
				
				OnPropertyChanged("PatientCode");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TID property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Tid
		{
			get
			{
				return this._tid; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "Tid does not allow null values.");
				if (_tid == value)
					return;
					
				this._tid = value;
				this._isDirty = true;
				
				OnPropertyChanged("Tid");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the FirstName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String FirstName
		{
			get
			{
				return this._firstName; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "FirstName does not allow null values.");
				if (_firstName == value)
					return;
					
				this._firstName = value;
				this._isDirty = true;
				
				OnPropertyChanged("FirstName");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the LastName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String LastName
		{
			get
			{
				return this._lastName; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "LastName does not allow null values.");
				if (_lastName == value)
					return;
					
				this._lastName = value;
				this._isDirty = true;
				
				OnPropertyChanged("LastName");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the DOB property. 
		///		
		/// </summary>
		/// <value>This type is datetime</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.DateTime Dob
		{
			get
			{
				return this._dob; 
			}
			set
			{
				if (_dob == value)
					return;
					
				this._dob = value;
				this._isDirty = true;
				
				OnPropertyChanged("Dob");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Sex property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Sex
		{
			get
			{
				return this._sex; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "Sex does not allow null values.");
				if (_sex == value)
					return;
					
				this._sex = value;
				this._isDirty = true;
				
				OnPropertyChanged("Sex");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Nationality property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Nationality
		{
			get
			{
				return this._nationality; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "Nationality does not allow null values.");
				if (_nationality == value)
					return;
					
				this._nationality = value;
				this._isDirty = true;
				
				OnPropertyChanged("Nationality");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the PatientStart property. 
		///		
		/// </summary>
		/// <value>This type is bit</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return false. It is up to the developer
		/// to check the value of IsPatientStartNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Boolean? PatientStart
		{
			get
			{
				return this._patientStart; 
			}
			set
			{
				if (_patientStart == value && PatientStart != null )
					return;
					
				this._patientStart = value;
				this._isDirty = true;
				
				OnPropertyChanged("PatientStart");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the VitalSign property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String VitalSign
		{
			get
			{
				return this._vitalSign; 
			}
			set
			{
				if (_vitalSign == value)
					return;
					
				this._vitalSign = value;
				this._isDirty = true;
				
				OnPropertyChanged("VitalSign");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Lab property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Lab
		{
			get
			{
				return this._lab; 
			}
			set
			{
				if (_lab == value)
					return;
					
				this._lab = value;
				this._isDirty = true;
				
				OnPropertyChanged("Lab");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Xray property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Xray
		{
			get
			{
				return this._xray; 
			}
			set
			{
				if (_xray == value)
					return;
					
				this._xray = value;
				this._isDirty = true;
				
				OnPropertyChanged("Xray");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the UltraSound property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String UltraSound
		{
			get
			{
				return this._ultraSound; 
			}
			set
			{
				if (_ultraSound == value)
					return;
					
				this._ultraSound = value;
				this._isDirty = true;
				
				OnPropertyChanged("UltraSound");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Cardiology property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Cardiology
		{
			get
			{
				return this._cardiology; 
			}
			set
			{
				if (_cardiology == value)
					return;
					
				this._cardiology = value;
				this._isDirty = true;
				
				OnPropertyChanged("Cardiology");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MedReport property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MedReport
		{
			get
			{
				return this._medReport; 
			}
			set
			{
				if (_medReport == value)
					return;
					
				this._medReport = value;
				this._isDirty = true;
				
				OnPropertyChanged("MedReport");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ChargedCodes property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String ChargedCodes
		{
			get
			{
				return this._chargedCodes; 
			}
			set
			{
				if (_chargedCodes == value)
					return;
					
				this._chargedCodes = value;
				this._isDirty = true;
				
				OnPropertyChanged("ChargedCodes");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the IsCompleted property. 
		///		
		/// </summary>
		/// <value>This type is bit</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return false. It is up to the developer
		/// to check the value of IsIsCompletedNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Boolean? IsCompleted
		{
			get
			{
				return this._isCompleted; 
			}
			set
			{
				if (_isCompleted == value && IsCompleted != null )
					return;
					
				this._isCompleted = value;
				this._isDirty = true;
				
				OnPropertyChanged("IsCompleted");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the CreateDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsCreateDateNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.DateTime? CreateDate
		{
			get
			{
				return this._createDate; 
			}
			set
			{
				if (_createDate == value && CreateDate != null )
					return;
					
				this._createDate = value;
				this._isDirty = true;
				
				OnPropertyChanged("CreateDate");
			}
		}
		
		
		/// <summary>
		///     Gets or sets the object that contains supplemental data about this object.
		/// </summary>
		/// <value>Object</value>
		[System.ComponentModel.Bindable(false)]
		[LocalizableAttribute(false)]
		[DescriptionAttribute("Object containing data to be associated with this object")]
		public virtual object Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if (this._tag == value)
					return;
		
				this._tag = value;
			}
		}
	
		/// <summary>
		/// Determines whether this entity is to suppress events while set to true.
		/// </summary>
		[System.ComponentModel.Bindable(false)]
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public bool SuppressEntityEvents
		{	
			get
			{
				return suppressEntityEvents;
			}
			set
			{
				suppressEntityEvents = value;
			}	
		}

		private bool _isDeleted = false;
		/// <summary>
		/// Gets a value indicating if object has been <see cref="MarkToDelete"/>. ReadOnly.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDeleted
		{
			get { return this._isDeleted; }
		}


		private bool _isDirty = false;
		/// <summary>
		///	Gets a value indicating  if the object has been modified from its original state.
		/// </summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDirty
		{
			get { return this._isDirty; }
		}
		

		private bool _isNew = true;
		/// <summary>
		///	Gets a value indicating if the object is new.
		/// </summary>
		///<value>True if objectis new; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsNew
		{
			get { return this._isNew; }
			set { this._isNew = value; }
		}

		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public string ViewName
		{
			get { return "Vr_DoctorDone"; }
		}

		
		#endregion
		
		#region Methods	
		
		/// <summary>
		/// Accepts the changes made to this object by setting each flags to false.
		/// </summary>
		public virtual void AcceptChanges()
		{
			this._isDeleted = false;
			this._isDirty = false;
			this._isNew = false;
			OnPropertyChanged(string.Empty);
		}
		
		
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		/// <exception cref="NotSupportedException">This method is not currently supported and always throws this exception.</exception>
		public virtual void CancelChanges()
		{
			throw new NotSupportedException("Method currently not Supported.");
		}
		
		///<summary>
		///   Marks entity to be deleted.
		///</summary>
		public virtual void MarkToDelete()
		{
			this._isDeleted = true;
		}
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed VrDoctorDoneBase Entity 
		///</summary>
		public virtual VrDoctorDoneBase Copy()
		{
			//shallow copy entity
			VrDoctorDone copy = new VrDoctorDone();
				copy.StatId = this.StatId;
				copy.PatientCode = this.PatientCode;
				copy.Tid = this.Tid;
				copy.FirstName = this.FirstName;
				copy.LastName = this.LastName;
				copy.Dob = this.Dob;
				copy.Sex = this.Sex;
				copy.Nationality = this.Nationality;
				copy.PatientStart = this.PatientStart;
				copy.VitalSign = this.VitalSign;
				copy.Lab = this.Lab;
				copy.Xray = this.Xray;
				copy.UltraSound = this.UltraSound;
				copy.Cardiology = this.Cardiology;
				copy.MedReport = this.MedReport;
				copy.ChargedCodes = this.ChargedCodes;
				copy.IsCompleted = this.IsCompleted;
				copy.CreateDate = this.CreateDate;
			copy.AcceptChanges();
			return (VrDoctorDone)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Deep Copy of this entity.
		///</summary>
		public object Clone(){
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		#endregion
		
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="VrDoctorDoneBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(VrDoctorDoneBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="VrDoctorDoneBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="VrDoctorDoneBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="VrDoctorDoneBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(VrDoctorDoneBase Object1, VrDoctorDoneBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;

			bool equal = true;
			if (Object1.StatId != Object2.StatId)
				equal = false;
			if (Object1.PatientCode != Object2.PatientCode)
				equal = false;
			if (Object1.Tid != Object2.Tid)
				equal = false;
			if (Object1.FirstName != Object2.FirstName)
				equal = false;
			if (Object1.LastName != Object2.LastName)
				equal = false;
			if (Object1.Dob != Object2.Dob)
				equal = false;
			if (Object1.Sex != Object2.Sex)
				equal = false;
			if (Object1.Nationality != Object2.Nationality)
				equal = false;
			if (Object1.PatientStart != null && Object2.PatientStart != null )
			{
				if (Object1.PatientStart != Object2.PatientStart)
					equal = false;
			}
			else if (Object1.PatientStart == null ^ Object1.PatientStart == null )
			{
				equal = false;
			}
			if (Object1.VitalSign != null && Object2.VitalSign != null )
			{
				if (Object1.VitalSign != Object2.VitalSign)
					equal = false;
			}
			else if (Object1.VitalSign == null ^ Object1.VitalSign == null )
			{
				equal = false;
			}
			if (Object1.Lab != null && Object2.Lab != null )
			{
				if (Object1.Lab != Object2.Lab)
					equal = false;
			}
			else if (Object1.Lab == null ^ Object1.Lab == null )
			{
				equal = false;
			}
			if (Object1.Xray != null && Object2.Xray != null )
			{
				if (Object1.Xray != Object2.Xray)
					equal = false;
			}
			else if (Object1.Xray == null ^ Object1.Xray == null )
			{
				equal = false;
			}
			if (Object1.UltraSound != null && Object2.UltraSound != null )
			{
				if (Object1.UltraSound != Object2.UltraSound)
					equal = false;
			}
			else if (Object1.UltraSound == null ^ Object1.UltraSound == null )
			{
				equal = false;
			}
			if (Object1.Cardiology != null && Object2.Cardiology != null )
			{
				if (Object1.Cardiology != Object2.Cardiology)
					equal = false;
			}
			else if (Object1.Cardiology == null ^ Object1.Cardiology == null )
			{
				equal = false;
			}
			if (Object1.MedReport != null && Object2.MedReport != null )
			{
				if (Object1.MedReport != Object2.MedReport)
					equal = false;
			}
			else if (Object1.MedReport == null ^ Object1.MedReport == null )
			{
				equal = false;
			}
			if (Object1.ChargedCodes != null && Object2.ChargedCodes != null )
			{
				if (Object1.ChargedCodes != Object2.ChargedCodes)
					equal = false;
			}
			else if (Object1.ChargedCodes == null ^ Object1.ChargedCodes == null )
			{
				equal = false;
			}
			if (Object1.IsCompleted != null && Object2.IsCompleted != null )
			{
				if (Object1.IsCompleted != Object2.IsCompleted)
					equal = false;
			}
			else if (Object1.IsCompleted == null ^ Object1.IsCompleted == null )
			{
				equal = false;
			}
			if (Object1.CreateDate != null && Object2.CreateDate != null )
			{
				if (Object1.CreateDate != Object2.CreateDate)
					equal = false;
			}
			else if (Object1.CreateDate == null ^ Object1.CreateDate == null )
			{
				equal = false;
			}
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
		}
	
		#endregion
		
		#region INotifyPropertyChanged Members
		
		/// <summary>
      /// Event to indicate that a property has changed.
      /// </summary>
		[field:NonSerialized]
		public event PropertyChangedEventHandler PropertyChanged;

		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="propertyName">The name of the property that has changed.</param>
		protected virtual void OnPropertyChanged(string propertyName)
		{ 
			OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
		}
		
		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="e">PropertyChangedEventArgs</param>
		protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
		{
			if (!SuppressEntityEvents)
			{
				if (null != PropertyChanged)
				{
					PropertyChanged(this, e);
				}
			}
		}
		
		#endregion
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="entity">The entity.</param>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public static object GetPropertyValueByName(VrDoctorDone entity, string propertyName)
		{
			switch (propertyName)
			{
				case "StatId":
					return entity.StatId;
				case "PatientCode":
					return entity.PatientCode;
				case "Tid":
					return entity.Tid;
				case "FirstName":
					return entity.FirstName;
				case "LastName":
					return entity.LastName;
				case "Dob":
					return entity.Dob;
				case "Sex":
					return entity.Sex;
				case "Nationality":
					return entity.Nationality;
				case "PatientStart":
					return entity.PatientStart;
				case "VitalSign":
					return entity.VitalSign;
				case "Lab":
					return entity.Lab;
				case "Xray":
					return entity.Xray;
				case "UltraSound":
					return entity.UltraSound;
				case "Cardiology":
					return entity.Cardiology;
				case "MedReport":
					return entity.MedReport;
				case "ChargedCodes":
					return entity.ChargedCodes;
				case "IsCompleted":
					return entity.IsCompleted;
				case "CreateDate":
					return entity.CreateDate;
			}
			return null;
		}
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public object GetPropertyValueByName(string propertyName)
		{			
			return GetPropertyValueByName(this as VrDoctorDone, propertyName);
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{19}{18}- StatId: {0}{18}- PatientCode: {1}{18}- Tid: {2}{18}- FirstName: {3}{18}- LastName: {4}{18}- Dob: {5}{18}- Sex: {6}{18}- Nationality: {7}{18}- PatientStart: {8}{18}- VitalSign: {9}{18}- Lab: {10}{18}- Xray: {11}{18}- UltraSound: {12}{18}- Cardiology: {13}{18}- MedReport: {14}{18}- ChargedCodes: {15}{18}- IsCompleted: {16}{18}- CreateDate: {17}{18}", 
				this.StatId,
				this.PatientCode,
				this.Tid,
				this.FirstName,
				this.LastName,
				this.Dob,
				this.Sex,
				this.Nationality,
				(this.PatientStart == null) ? string.Empty : this.PatientStart.ToString(),
			     
				(this.VitalSign == null) ? string.Empty : this.VitalSign.ToString(),
			     
				(this.Lab == null) ? string.Empty : this.Lab.ToString(),
			     
				(this.Xray == null) ? string.Empty : this.Xray.ToString(),
			     
				(this.UltraSound == null) ? string.Empty : this.UltraSound.ToString(),
			     
				(this.Cardiology == null) ? string.Empty : this.Cardiology.ToString(),
			     
				(this.MedReport == null) ? string.Empty : this.MedReport.ToString(),
			     
				(this.ChargedCodes == null) ? string.Empty : this.ChargedCodes.ToString(),
			     
				(this.IsCompleted == null) ? string.Empty : this.IsCompleted.ToString(),
			     
				(this.CreateDate == null) ? string.Empty : this.CreateDate.ToString(),
			     
				System.Environment.NewLine, 
				this.GetType());
		}
	
	}//End Class
	
	
	/// <summary>
	/// Enumerate the VrDoctorDone columns.
	/// </summary>
	[Serializable]
	public enum VrDoctorDoneColumn
	{
		/// <summary>
		/// StatId : 
		/// </summary>
		[EnumTextValue("StatId")]
		[ColumnEnum("StatId", typeof(System.Int64), System.Data.DbType.Int64, false, false, false)]
		StatId,
		/// <summary>
		/// PatientCode : 
		/// </summary>
		[EnumTextValue("PatientCode")]
		[ColumnEnum("PatientCode", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		PatientCode,
		/// <summary>
		/// TID : 
		/// </summary>
		[EnumTextValue("TID")]
		[ColumnEnum("TID", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		Tid,
		/// <summary>
		/// FirstName : 
		/// </summary>
		[EnumTextValue("FirstName")]
		[ColumnEnum("FirstName", typeof(System.String), System.Data.DbType.String, false, false, false, 30)]
		FirstName,
		/// <summary>
		/// LastName : 
		/// </summary>
		[EnumTextValue("LastName")]
		[ColumnEnum("LastName", typeof(System.String), System.Data.DbType.String, false, false, false, 30)]
		LastName,
		/// <summary>
		/// DOB : 
		/// </summary>
		[EnumTextValue("DOB")]
		[ColumnEnum("DOB", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Dob,
		/// <summary>
		/// Sex : 
		/// </summary>
		[EnumTextValue("Sex")]
		[ColumnEnum("Sex", typeof(System.String), System.Data.DbType.String, false, false, false, 10)]
		Sex,
		/// <summary>
		/// Nationality : 
		/// </summary>
		[EnumTextValue("Nationality")]
		[ColumnEnum("Nationality", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		Nationality,
		/// <summary>
		/// PatientStart : 
		/// </summary>
		[EnumTextValue("PatientStart")]
		[ColumnEnum("PatientStart", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		PatientStart,
		/// <summary>
		/// VitalSign : 
		/// </summary>
		[EnumTextValue("VitalSign")]
		[ColumnEnum("VitalSign", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		VitalSign,
		/// <summary>
		/// Lab : 
		/// </summary>
		[EnumTextValue("Lab")]
		[ColumnEnum("Lab", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Lab,
		/// <summary>
		/// Xray : 
		/// </summary>
		[EnumTextValue("Xray")]
		[ColumnEnum("Xray", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Xray,
		/// <summary>
		/// UltraSound : 
		/// </summary>
		[EnumTextValue("UltraSound")]
		[ColumnEnum("UltraSound", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		UltraSound,
		/// <summary>
		/// Cardiology : 
		/// </summary>
		[EnumTextValue("Cardiology")]
		[ColumnEnum("Cardiology", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Cardiology,
		/// <summary>
		/// MedReport : 
		/// </summary>
		[EnumTextValue("MedReport")]
		[ColumnEnum("MedReport", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		MedReport,
		/// <summary>
		/// ChargedCodes : 
		/// </summary>
		[EnumTextValue("ChargedCodes")]
		[ColumnEnum("ChargedCodes", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		ChargedCodes,
		/// <summary>
		/// IsCompleted : 
		/// </summary>
		[EnumTextValue("IsCompleted")]
		[ColumnEnum("IsCompleted", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		IsCompleted,
		/// <summary>
		/// CreateDate : 
		/// </summary>
		[EnumTextValue("CreateDate")]
		[ColumnEnum("CreateDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		CreateDate
	}//End enum

} // end namespace
