/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file VrMedPro.cs instead.
*/
#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Runtime.Serialization;
using System.Xml.Serialization;
#endregion

namespace ePrescription.Entities
{
	///<summary>
	/// An object representation of the 'Vr_MedPro' view. [No description found in the database]	
	///</summary>
	[Serializable]
	[CLSCompliant(true)]
	[ToolboxItem("VrMedProBase")]
	public abstract partial class VrMedProBase : System.IComparable, System.ICloneable, INotifyPropertyChanged
	{
		
		#region Variable Declarations
		
		/// <summary>
		/// PRO_CODE : 
		/// </summary>
		private System.String		  _proCode = string.Empty;
		
		/// <summary>
		/// Description : 
		/// </summary>
		private System.String		  _description = null;
		
		/// <summary>
		/// MAIN_AREA : 
		/// </summary>
		private System.String		  _mainArea = null;
		
		/// <summary>
		/// PUB_PRICE : 
		/// </summary>
		private System.Decimal		  _pubPrice = 0.0m;
		
		/// <summary>
		/// SampleType : 
		/// </summary>
		private System.String		  _sampleType = null;
		
		/// <summary>
		/// ProviderType : 
		/// </summary>
		private System.String		  _providerType = null;
		
		/// <summary>
		/// Object that contains data to associate with this object
		/// </summary>
		private object _tag;
		
		/// <summary>
		/// Suppresses Entity Events from Firing, 
		/// useful when loading the entities from the database.
		/// </summary>
	    [NonSerialized] 
		private bool suppressEntityEvents = false;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="VrMedProBase"/> instance.
		///</summary>
		public VrMedProBase()
		{
		}		
		
		///<summary>
		/// Creates a new <see cref="VrMedProBase"/> instance.
		///</summary>
		///<param name="_proCode"></param>
		///<param name="_description"></param>
		///<param name="_mainArea"></param>
		///<param name="_pubPrice"></param>
		///<param name="_sampleType"></param>
		///<param name="_providerType"></param>
		public VrMedProBase(System.String _proCode, System.String _description, System.String _mainArea, System.Decimal _pubPrice, System.String _sampleType, System.String _providerType)
		{
			this._proCode = _proCode;
			this._description = _description;
			this._mainArea = _mainArea;
			this._pubPrice = _pubPrice;
			this._sampleType = _sampleType;
			this._providerType = _providerType;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="VrMedPro"/> instance.
		///</summary>
		///<param name="_proCode"></param>
		///<param name="_description"></param>
		///<param name="_mainArea"></param>
		///<param name="_pubPrice"></param>
		///<param name="_sampleType"></param>
		///<param name="_providerType"></param>
		public static VrMedPro CreateVrMedPro(System.String _proCode, System.String _description, System.String _mainArea, System.Decimal _pubPrice, System.String _sampleType, System.String _providerType)
		{
			VrMedPro newVrMedPro = new VrMedPro();
			newVrMedPro.ProCode = _proCode;
			newVrMedPro.Description = _description;
			newVrMedPro.MainArea = _mainArea;
			newVrMedPro.PubPrice = _pubPrice;
			newVrMedPro.SampleType = _sampleType;
			newVrMedPro.ProviderType = _providerType;
			return newVrMedPro;
		}
				
		#endregion Constructors
		
		#region Properties	
		/// <summary>
		/// 	Gets or Sets the PRO_CODE property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String ProCode
		{
			get
			{
				return this._proCode; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "ProCode does not allow null values.");
				if (_proCode == value)
					return;
					
				this._proCode = value;
				this._isDirty = true;
				
				OnPropertyChanged("ProCode");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Description
		{
			get
			{
				return this._description; 
			}
			set
			{
				if (_description == value)
					return;
					
				this._description = value;
				this._isDirty = true;
				
				OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MAIN_AREA property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MainArea
		{
			get
			{
				return this._mainArea; 
			}
			set
			{
				if (_mainArea == value)
					return;
					
				this._mainArea = value;
				this._isDirty = true;
				
				OnPropertyChanged("MainArea");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the PUB_PRICE property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal PubPrice
		{
			get
			{
				return this._pubPrice; 
			}
			set
			{
				if (_pubPrice == value)
					return;
					
				this._pubPrice = value;
				this._isDirty = true;
				
				OnPropertyChanged("PubPrice");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the SampleType property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String SampleType
		{
			get
			{
				return this._sampleType; 
			}
			set
			{
				if (_sampleType == value)
					return;
					
				this._sampleType = value;
				this._isDirty = true;
				
				OnPropertyChanged("SampleType");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ProviderType property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String ProviderType
		{
			get
			{
				return this._providerType; 
			}
			set
			{
				if (_providerType == value)
					return;
					
				this._providerType = value;
				this._isDirty = true;
				
				OnPropertyChanged("ProviderType");
			}
		}
		
		
		/// <summary>
		///     Gets or sets the object that contains supplemental data about this object.
		/// </summary>
		/// <value>Object</value>
		[System.ComponentModel.Bindable(false)]
		[LocalizableAttribute(false)]
		[DescriptionAttribute("Object containing data to be associated with this object")]
		public virtual object Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if (this._tag == value)
					return;
		
				this._tag = value;
			}
		}
	
		/// <summary>
		/// Determines whether this entity is to suppress events while set to true.
		/// </summary>
		[System.ComponentModel.Bindable(false)]
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public bool SuppressEntityEvents
		{	
			get
			{
				return suppressEntityEvents;
			}
			set
			{
				suppressEntityEvents = value;
			}	
		}

		private bool _isDeleted = false;
		/// <summary>
		/// Gets a value indicating if object has been <see cref="MarkToDelete"/>. ReadOnly.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDeleted
		{
			get { return this._isDeleted; }
		}


		private bool _isDirty = false;
		/// <summary>
		///	Gets a value indicating  if the object has been modified from its original state.
		/// </summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDirty
		{
			get { return this._isDirty; }
		}
		

		private bool _isNew = true;
		/// <summary>
		///	Gets a value indicating if the object is new.
		/// </summary>
		///<value>True if objectis new; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsNew
		{
			get { return this._isNew; }
			set { this._isNew = value; }
		}

		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public string ViewName
		{
			get { return "Vr_MedPro"; }
		}

		
		#endregion
		
		#region Methods	
		
		/// <summary>
		/// Accepts the changes made to this object by setting each flags to false.
		/// </summary>
		public virtual void AcceptChanges()
		{
			this._isDeleted = false;
			this._isDirty = false;
			this._isNew = false;
			OnPropertyChanged(string.Empty);
		}
		
		
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		/// <exception cref="NotSupportedException">This method is not currently supported and always throws this exception.</exception>
		public virtual void CancelChanges()
		{
			throw new NotSupportedException("Method currently not Supported.");
		}
		
		///<summary>
		///   Marks entity to be deleted.
		///</summary>
		public virtual void MarkToDelete()
		{
			this._isDeleted = true;
		}
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed VrMedProBase Entity 
		///</summary>
		public virtual VrMedProBase Copy()
		{
			//shallow copy entity
			VrMedPro copy = new VrMedPro();
				copy.ProCode = this.ProCode;
				copy.Description = this.Description;
				copy.MainArea = this.MainArea;
				copy.PubPrice = this.PubPrice;
				copy.SampleType = this.SampleType;
				copy.ProviderType = this.ProviderType;
			copy.AcceptChanges();
			return (VrMedPro)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Deep Copy of this entity.
		///</summary>
		public object Clone(){
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		#endregion
		
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="VrMedProBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(VrMedProBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="VrMedProBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="VrMedProBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="VrMedProBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(VrMedProBase Object1, VrMedProBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;

			bool equal = true;
			if (Object1.ProCode != Object2.ProCode)
				equal = false;
			if (Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object1.Description == null )
			{
				equal = false;
			}
			if (Object1.MainArea != null && Object2.MainArea != null )
			{
				if (Object1.MainArea != Object2.MainArea)
					equal = false;
			}
			else if (Object1.MainArea == null ^ Object1.MainArea == null )
			{
				equal = false;
			}
			if (Object1.PubPrice != Object2.PubPrice)
				equal = false;
			if (Object1.SampleType != null && Object2.SampleType != null )
			{
				if (Object1.SampleType != Object2.SampleType)
					equal = false;
			}
			else if (Object1.SampleType == null ^ Object1.SampleType == null )
			{
				equal = false;
			}
			if (Object1.ProviderType != null && Object2.ProviderType != null )
			{
				if (Object1.ProviderType != Object2.ProviderType)
					equal = false;
			}
			else if (Object1.ProviderType == null ^ Object1.ProviderType == null )
			{
				equal = false;
			}
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
		}
	
		#endregion
		
		#region INotifyPropertyChanged Members
		
		/// <summary>
      /// Event to indicate that a property has changed.
      /// </summary>
		[field:NonSerialized]
		public event PropertyChangedEventHandler PropertyChanged;

		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="propertyName">The name of the property that has changed.</param>
		protected virtual void OnPropertyChanged(string propertyName)
		{ 
			OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
		}
		
		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="e">PropertyChangedEventArgs</param>
		protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
		{
			if (!SuppressEntityEvents)
			{
				if (null != PropertyChanged)
				{
					PropertyChanged(this, e);
				}
			}
		}
		
		#endregion
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="entity">The entity.</param>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public static object GetPropertyValueByName(VrMedPro entity, string propertyName)
		{
			switch (propertyName)
			{
				case "ProCode":
					return entity.ProCode;
				case "Description":
					return entity.Description;
				case "MainArea":
					return entity.MainArea;
				case "PubPrice":
					return entity.PubPrice;
				case "SampleType":
					return entity.SampleType;
				case "ProviderType":
					return entity.ProviderType;
			}
			return null;
		}
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public object GetPropertyValueByName(string propertyName)
		{			
			return GetPropertyValueByName(this as VrMedPro, propertyName);
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- ProCode: {0}{6}- Description: {1}{6}- MainArea: {2}{6}- PubPrice: {3}{6}- SampleType: {4}{6}- ProviderType: {5}{6}", 
				this.ProCode,
				(this.Description == null) ? string.Empty : this.Description.ToString(),
			     
				(this.MainArea == null) ? string.Empty : this.MainArea.ToString(),
			     
				this.PubPrice,
				(this.SampleType == null) ? string.Empty : this.SampleType.ToString(),
			     
				(this.ProviderType == null) ? string.Empty : this.ProviderType.ToString(),
			     
				System.Environment.NewLine, 
				this.GetType());
		}
	
	}//End Class
	
	
	/// <summary>
	/// Enumerate the VrMedPro columns.
	/// </summary>
	[Serializable]
	public enum VrMedProColumn
	{
		/// <summary>
		/// PRO_CODE : 
		/// </summary>
		[EnumTextValue("PRO_CODE")]
		[ColumnEnum("PRO_CODE", typeof(System.String), System.Data.DbType.String, false, false, false, 255)]
		ProCode,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("Description", typeof(System.String), System.Data.DbType.String, false, false, true, 513)]
		Description,
		/// <summary>
		/// MAIN_AREA : 
		/// </summary>
		[EnumTextValue("MAIN_AREA")]
		[ColumnEnum("MAIN_AREA", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		MainArea,
		/// <summary>
		/// PUB_PRICE : 
		/// </summary>
		[EnumTextValue("PUB_PRICE")]
		[ColumnEnum("PUB_PRICE", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, false)]
		PubPrice,
		/// <summary>
		/// SampleType : 
		/// </summary>
		[EnumTextValue("SampleType")]
		[ColumnEnum("SampleType", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		SampleType,
		/// <summary>
		/// ProviderType : 
		/// </summary>
		[EnumTextValue("ProviderType")]
		[ColumnEnum("ProviderType", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		ProviderType
	}//End enum

} // end namespace
