
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file DoctorRequest.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using ePrescription.Entities.Validation;
#endregion

namespace ePrescription.Entities
{
	///<summary>
	/// An object representation of the 'DoctorRequest' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class DoctorRequestBase : EntityBase, IDoctorRequest, IEntityId<DoctorRequestKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private DoctorRequestEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private DoctorRequestEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private DoctorRequestEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<DoctorRequest> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DoctorRequestEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DoctorRequestEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="DoctorRequestBase"/> instance.
		///</summary>
		public DoctorRequestBase()
		{
			this.entityData = new DoctorRequestEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="DoctorRequestBase"/> instance.
		///</summary>
		///<param name="_tid"></param>
		///<param name="_reqId"></param>
		///<param name="_code"></param>
		///<param name="_description"></param>
		///<param name="_reqDoctor"></param>
		///<param name="_reqDate"></param>
		///<param name="_reqStatus"></param>
		///<param name="_billable"></param>
		///<param name="_sample"></param>
		public DoctorRequestBase(System.String _tid, System.String _reqId, System.String _code, 
			System.String _description, System.String _reqDoctor, System.DateTime? _reqDate, System.String _reqStatus, 
			System.Boolean? _billable, System.String _sample)
		{
			this.entityData = new DoctorRequestEntityData();
			this.backupData = null;

			this.Tid = _tid;
			this.ReqId = _reqId;
			this.Code = _code;
			this.Description = _description;
			this.ReqDoctor = _reqDoctor;
			this.ReqDate = _reqDate;
			this.ReqStatus = _reqStatus;
			this.Billable = _billable;
			this.Sample = _sample;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="DoctorRequest"/> instance.
		///</summary>
		///<param name="_tid"></param>
		///<param name="_reqId"></param>
		///<param name="_code"></param>
		///<param name="_description"></param>
		///<param name="_reqDoctor"></param>
		///<param name="_reqDate"></param>
		///<param name="_reqStatus"></param>
		///<param name="_billable"></param>
		///<param name="_sample"></param>
		public static DoctorRequest CreateDoctorRequest(System.String _tid, System.String _reqId, System.String _code, 
			System.String _description, System.String _reqDoctor, System.DateTime? _reqDate, System.String _reqStatus, 
			System.Boolean? _billable, System.String _sample)
		{
			DoctorRequest newDoctorRequest = new DoctorRequest();
			newDoctorRequest.Tid = _tid;
			newDoctorRequest.ReqId = _reqId;
			newDoctorRequest.Code = _code;
			newDoctorRequest.Description = _description;
			newDoctorRequest.ReqDoctor = _reqDoctor;
			newDoctorRequest.ReqDate = _reqDate;
			newDoctorRequest.ReqStatus = _reqStatus;
			newDoctorRequest.Billable = _billable;
			newDoctorRequest.Sample = _sample;
			return newDoctorRequest;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Id is required")]




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(DoctorRequestColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Tid property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Tid
		{
			get
			{
				return this.entityData.Tid; 
			}
			
			set
			{
				if (this.entityData.Tid == value)
					return;
				
                OnPropertyChanging("Tid");                    
				OnColumnChanging(DoctorRequestColumn.Tid, this.entityData.Tid);
				this.entityData.Tid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.Tid, this.entityData.Tid);
				OnPropertyChanged("Tid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ReqId property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String ReqId
		{
			get
			{
				return this.entityData.ReqId; 
			}
			
			set
			{
				if (this.entityData.ReqId == value)
					return;
				
                OnPropertyChanging("ReqId");                    
				OnColumnChanging(DoctorRequestColumn.ReqId, this.entityData.ReqId);
				this.entityData.ReqId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.ReqId, this.entityData.ReqId);
				OnPropertyChanged("ReqId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Code property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String Code
		{
			get
			{
				return this.entityData.Code; 
			}
			
			set
			{
				if (this.entityData.Code == value)
					return;
				
                OnPropertyChanging("Code");                    
				OnColumnChanging(DoctorRequestColumn.Code, this.entityData.Code);
				this.entityData.Code = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.Code, this.entityData.Code);
				OnPropertyChanged("Code");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 250)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
				
                OnPropertyChanging("Description");                    
				OnColumnChanging(DoctorRequestColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ReqDoctor property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String ReqDoctor
		{
			get
			{
				return this.entityData.ReqDoctor; 
			}
			
			set
			{
				if (this.entityData.ReqDoctor == value)
					return;
				
                OnPropertyChanging("ReqDoctor");                    
				OnColumnChanging(DoctorRequestColumn.ReqDoctor, this.entityData.ReqDoctor);
				this.entityData.ReqDoctor = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.ReqDoctor, this.entityData.ReqDoctor);
				OnPropertyChanged("ReqDoctor");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ReqDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ReqDate
		{
			get
			{
				return this.entityData.ReqDate; 
			}
			
			set
			{
				if (this.entityData.ReqDate == value)
					return;
				
                OnPropertyChanging("ReqDate");                    
				OnColumnChanging(DoctorRequestColumn.ReqDate, this.entityData.ReqDate);
				this.entityData.ReqDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.ReqDate, this.entityData.ReqDate);
				OnPropertyChanged("ReqDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ReqStatus property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String ReqStatus
		{
			get
			{
				return this.entityData.ReqStatus; 
			}
			
			set
			{
				if (this.entityData.ReqStatus == value)
					return;
				
                OnPropertyChanging("ReqStatus");                    
				OnColumnChanging(DoctorRequestColumn.ReqStatus, this.entityData.ReqStatus);
				this.entityData.ReqStatus = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.ReqStatus, this.entityData.ReqStatus);
				OnPropertyChanged("ReqStatus");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Billable property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? Billable
		{
			get
			{
				return this.entityData.Billable; 
			}
			
			set
			{
				if (this.entityData.Billable == value)
					return;
				
                OnPropertyChanging("Billable");                    
				OnColumnChanging(DoctorRequestColumn.Billable, this.entityData.Billable);
				this.entityData.Billable = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.Billable, this.entityData.Billable);
				OnPropertyChanged("Billable");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Sample property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Sample
		{
			get
			{
				return this.entityData.Sample; 
			}
			
			set
			{
				if (this.entityData.Sample == value)
					return;
				
                OnPropertyChanging("Sample");                    
				OnColumnChanging(DoctorRequestColumn.Sample, this.entityData.Sample);
				this.entityData.Sample = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorRequestColumn.Sample, this.entityData.Sample);
				OnPropertyChanged("Sample");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Tid", "Tid", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ReqId", "Req Id", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Code", "Code", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Description", "Description", 250));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ReqDoctor", "Req Doctor", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ReqStatus", "Req Status", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Sample", "Sample", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "DoctorRequest"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "TID", "ReqID", "Code", "Description", "ReqDoctor", "ReqDate", "ReqStatus", "Billable", "Sample"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as DoctorRequestEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (DoctorRequest) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<DoctorRequest>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as DoctorRequest);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed DoctorRequest Entity 
		///</summary>
		protected virtual DoctorRequest Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			DoctorRequest copy = new DoctorRequest();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.Tid = this.Tid;
				copy.ReqId = this.ReqId;
				copy.Code = this.Code;
				copy.Description = this.Description;
				copy.ReqDoctor = this.ReqDoctor;
				copy.ReqDate = this.ReqDate;
				copy.ReqStatus = this.ReqStatus;
				copy.Billable = this.Billable;
				copy.Sample = this.Sample;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed DoctorRequest Entity 
		///</summary>
		public virtual DoctorRequest Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed DoctorRequest Entity which is a deep copy of the current entity.
		///</summary>
		public virtual DoctorRequest DeepCopy()
		{
			return EntityHelper.Clone<DoctorRequest>(this as DoctorRequest);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as DoctorRequestEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new DoctorRequestEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as DoctorRequestEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(DoctorRequestColumn column)
		{
			switch(column)
			{
					case DoctorRequestColumn.Id:
					return entityData.Id != _originalData.Id;
					case DoctorRequestColumn.Tid:
					return entityData.Tid != _originalData.Tid;
					case DoctorRequestColumn.ReqId:
					return entityData.ReqId != _originalData.ReqId;
					case DoctorRequestColumn.Code:
					return entityData.Code != _originalData.Code;
					case DoctorRequestColumn.Description:
					return entityData.Description != _originalData.Description;
					case DoctorRequestColumn.ReqDoctor:
					return entityData.ReqDoctor != _originalData.ReqDoctor;
					case DoctorRequestColumn.ReqDate:
					return entityData.ReqDate != _originalData.ReqDate;
					case DoctorRequestColumn.ReqStatus:
					return entityData.ReqStatus != _originalData.ReqStatus;
					case DoctorRequestColumn.Billable:
					return entityData.Billable != _originalData.Billable;
					case DoctorRequestColumn.Sample:
					return entityData.Sample != _originalData.Sample;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< DoctorRequestColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.Tid != _originalData.Tid;
			result = result || entityData.ReqId != _originalData.ReqId;
			result = result || entityData.Code != _originalData.Code;
			result = result || entityData.Description != _originalData.Description;
			result = result || entityData.ReqDoctor != _originalData.ReqDoctor;
			result = result || entityData.ReqDate != _originalData.ReqDate;
			result = result || entityData.ReqStatus != _originalData.ReqStatus;
			result = result || entityData.Billable != _originalData.Billable;
			result = result || entityData.Sample != _originalData.Sample;
			return result;
		}	
		
		///<summary>
		///  Returns a DoctorRequest Entity with the original data.
		///</summary>
		public DoctorRequest GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateDoctorRequest(
				_originalData.Tid,
				_originalData.ReqId,
				_originalData.Code,
				_originalData.Description,
				_originalData.ReqDoctor,
				_originalData.ReqDate,
				_originalData.ReqStatus,
				_originalData.Billable,
				_originalData.Sample
				);
				
			return (DoctorRequest)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="DoctorRequestBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is DoctorRequestBase)
				return ValueEquals(this, (DoctorRequestBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="DoctorRequestBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.Tid == null) ? string.Empty : this.Tid.ToString()).GetHashCode() ^ 
					((this.ReqId == null) ? string.Empty : this.ReqId.ToString()).GetHashCode() ^ 
					((this.Code == null) ? string.Empty : this.Code.ToString()).GetHashCode() ^ 
					((this.Description == null) ? string.Empty : this.Description.ToString()).GetHashCode() ^ 
					((this.ReqDoctor == null) ? string.Empty : this.ReqDoctor.ToString()).GetHashCode() ^ 
					((this.ReqDate == null) ? string.Empty : this.ReqDate.ToString()).GetHashCode() ^ 
					((this.ReqStatus == null) ? string.Empty : this.ReqStatus.ToString()).GetHashCode() ^ 
					((this.Billable == null) ? string.Empty : this.Billable.ToString()).GetHashCode() ^ 
					((this.Sample == null) ? string.Empty : this.Sample.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="DoctorRequestBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(DoctorRequestBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="DoctorRequestBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="DoctorRequestBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="DoctorRequestBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(DoctorRequestBase Object1, DoctorRequestBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.Tid != null && Object2.Tid != null )
			{
				if (Object1.Tid != Object2.Tid)
					equal = false;
			}
			else if (Object1.Tid == null ^ Object2.Tid == null )
			{
				equal = false;
			}
			if ( Object1.ReqId != null && Object2.ReqId != null )
			{
				if (Object1.ReqId != Object2.ReqId)
					equal = false;
			}
			else if (Object1.ReqId == null ^ Object2.ReqId == null )
			{
				equal = false;
			}
			if ( Object1.Code != null && Object2.Code != null )
			{
				if (Object1.Code != Object2.Code)
					equal = false;
			}
			else if (Object1.Code == null ^ Object2.Code == null )
			{
				equal = false;
			}
			if ( Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object2.Description == null )
			{
				equal = false;
			}
			if ( Object1.ReqDoctor != null && Object2.ReqDoctor != null )
			{
				if (Object1.ReqDoctor != Object2.ReqDoctor)
					equal = false;
			}
			else if (Object1.ReqDoctor == null ^ Object2.ReqDoctor == null )
			{
				equal = false;
			}
			if ( Object1.ReqDate != null && Object2.ReqDate != null )
			{
				if (Object1.ReqDate != Object2.ReqDate)
					equal = false;
			}
			else if (Object1.ReqDate == null ^ Object2.ReqDate == null )
			{
				equal = false;
			}
			if ( Object1.ReqStatus != null && Object2.ReqStatus != null )
			{
				if (Object1.ReqStatus != Object2.ReqStatus)
					equal = false;
			}
			else if (Object1.ReqStatus == null ^ Object2.ReqStatus == null )
			{
				equal = false;
			}
			if ( Object1.Billable != null && Object2.Billable != null )
			{
				if (Object1.Billable != Object2.Billable)
					equal = false;
			}
			else if (Object1.Billable == null ^ Object2.Billable == null )
			{
				equal = false;
			}
			if ( Object1.Sample != null && Object2.Sample != null )
			{
				if (Object1.Sample != Object2.Sample)
					equal = false;
			}
			else if (Object1.Sample == null ^ Object2.Sample == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((DoctorRequestBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static DoctorRequestComparer GetComparer()
        {
            return new DoctorRequestComparer();
        }
        */

        // Comparer delegates back to DoctorRequest
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(DoctorRequest rhs, DoctorRequestColumn which)
        {
            switch (which)
            {
            	
            	
            	case DoctorRequestColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case DoctorRequestColumn.Tid:
            		return this.Tid.CompareTo(rhs.Tid);
            		
            		                 
            	
            	
            	case DoctorRequestColumn.ReqId:
            		return this.ReqId.CompareTo(rhs.ReqId);
            		
            		                 
            	
            	
            	case DoctorRequestColumn.Code:
            		return this.Code.CompareTo(rhs.Code);
            		
            		                 
            	
            	
            	case DoctorRequestColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            	
            	
            	case DoctorRequestColumn.ReqDoctor:
            		return this.ReqDoctor.CompareTo(rhs.ReqDoctor);
            		
            		                 
            	
            	
            	case DoctorRequestColumn.ReqDate:
            		return this.ReqDate.Value.CompareTo(rhs.ReqDate.Value);
            		
            		                 
            	
            	
            	case DoctorRequestColumn.ReqStatus:
            		return this.ReqStatus.CompareTo(rhs.ReqStatus);
            		
            		                 
            	
            	
            	case DoctorRequestColumn.Billable:
            		return this.Billable.Value.CompareTo(rhs.Billable.Value);
            		
            		                 
            	
            	
            	case DoctorRequestColumn.Sample:
            		return this.Sample.CompareTo(rhs.Sample);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<DoctorRequestKey> Members
		
		// member variable for the EntityId property
		private DoctorRequestKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual DoctorRequestKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new DoctorRequestKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("DoctorRequest")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{11}{10}- Id: {0}{10}- Tid: {1}{10}- ReqId: {2}{10}- Code: {3}{10}- Description: {4}{10}- ReqDoctor: {5}{10}- ReqDate: {6}{10}- ReqStatus: {7}{10}- Billable: {8}{10}- Sample: {9}{10}{12}", 
				this.Id,
				(this.Tid == null) ? string.Empty : this.Tid.ToString(),
				(this.ReqId == null) ? string.Empty : this.ReqId.ToString(),
				(this.Code == null) ? string.Empty : this.Code.ToString(),
				(this.Description == null) ? string.Empty : this.Description.ToString(),
				(this.ReqDoctor == null) ? string.Empty : this.ReqDoctor.ToString(),
				(this.ReqDate == null) ? string.Empty : this.ReqDate.ToString(),
				(this.ReqStatus == null) ? string.Empty : this.ReqStatus.ToString(),
				(this.Billable == null) ? string.Empty : this.Billable.ToString(),
				(this.Sample == null) ? string.Empty : this.Sample.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'DoctorRequest' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class DoctorRequestEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "DoctorRequest"</remarks>
		public System.Int64 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// TID : 
		/// </summary>
		public System.String Tid = null;
		
		/// <summary>
		/// ReqID : 
		/// </summary>
		public System.String ReqId = null;
		
		/// <summary>
		/// Code : 
		/// </summary>
		public System.String Code = null;
		
		/// <summary>
		/// Description : 
		/// </summary>
		public System.String Description = null;
		
		/// <summary>
		/// ReqDoctor : 
		/// </summary>
		public System.String ReqDoctor = null;
		
		/// <summary>
		/// ReqDate : 
		/// </summary>
		public System.DateTime? ReqDate = null;
		
		/// <summary>
		/// ReqStatus : 
		/// </summary>
		public System.String ReqStatus = null;
		
		/// <summary>
		/// Billable : 
		/// </summary>
		public System.Boolean? Billable = null;
		
		/// <summary>
		/// Sample : 
		/// </summary>
		public System.String Sample = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			DoctorRequestEntityData _tmp = new DoctorRequestEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.Tid = this.Tid;
			_tmp.ReqId = this.ReqId;
			_tmp.Code = this.Code;
			_tmp.Description = this.Description;
			_tmp.ReqDoctor = this.ReqDoctor;
			_tmp.ReqDate = this.ReqDate;
			_tmp.ReqStatus = this.ReqStatus;
			_tmp.Billable = this.Billable;
			_tmp.Sample = this.Sample;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			DoctorRequestEntityData _tmp = new DoctorRequestEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.Tid = this.Tid;
			_tmp.ReqId = this.ReqId;
			_tmp.Code = this.Code;
			_tmp.Description = this.Description;
			_tmp.ReqDoctor = this.ReqDoctor;
			_tmp.ReqDate = this.ReqDate;
			_tmp.ReqStatus = this.ReqStatus;
			_tmp.Billable = this.Billable;
			_tmp.Sample = this.Sample;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DoctorRequestColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(DoctorRequestColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DoctorRequestColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(DoctorRequestColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DoctorRequestColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(DoctorRequestColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				DoctorRequestEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new DoctorRequestEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DoctorRequestColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(DoctorRequestColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				DoctorRequestEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new DoctorRequestEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region DoctorRequestEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="DoctorRequest"/> object.
	/// </remarks>
	public class DoctorRequestEventArgs : System.EventArgs
	{
		private DoctorRequestColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the DoctorRequestEventArgs class.
		///</summary>
		public DoctorRequestEventArgs(DoctorRequestColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the DoctorRequestEventArgs class.
		///</summary>
		public DoctorRequestEventArgs(DoctorRequestColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The DoctorRequestColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="DoctorRequestColumn" />
		public DoctorRequestColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all DoctorRequest related events.
	///</summary>
	public delegate void DoctorRequestEventHandler(object sender, DoctorRequestEventArgs e);
	
	#region DoctorRequestComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class DoctorRequestComparer : System.Collections.Generic.IComparer<DoctorRequest>
	{
		DoctorRequestColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:DoctorRequestComparer"/> class.
        /// </summary>
		public DoctorRequestComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:DoctorRequestComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public DoctorRequestComparer(DoctorRequestColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="DoctorRequest"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="DoctorRequest"/> to compare.</param>
        /// <param name="b">The second <c>DoctorRequest</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(DoctorRequest a, DoctorRequest b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(DoctorRequest entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(DoctorRequest a, DoctorRequest b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public DoctorRequestColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region DoctorRequestKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="DoctorRequest"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class DoctorRequestKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the DoctorRequestKey class.
		/// </summary>
		public DoctorRequestKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the DoctorRequestKey class.
		/// </summary>
		public DoctorRequestKey(DoctorRequestBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the DoctorRequestKey class.
		/// </summary>
		public DoctorRequestKey(System.Int64 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private DoctorRequestBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public DoctorRequestBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int64 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int64 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["Id"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region DoctorRequestColumn Enum
	
	/// <summary>
	/// Enumerate the DoctorRequest columns.
	/// </summary>
	[Serializable]
	public enum DoctorRequestColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		Id = 1,
		/// <summary>
		/// Tid : 
		/// </summary>
		[EnumTextValue("Tid")]
		[ColumnEnum("TID", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Tid = 2,
		/// <summary>
		/// ReqId : 
		/// </summary>
		[EnumTextValue("Req Id")]
		[ColumnEnum("ReqID", typeof(System.String), System.Data.DbType.String, false, false, true, 10)]
		ReqId = 3,
		/// <summary>
		/// Code : 
		/// </summary>
		[EnumTextValue("Code")]
		[ColumnEnum("Code", typeof(System.String), System.Data.DbType.String, false, false, true, 10)]
		Code = 4,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("Description", typeof(System.String), System.Data.DbType.String, false, false, true, 250)]
		Description = 5,
		/// <summary>
		/// ReqDoctor : 
		/// </summary>
		[EnumTextValue("Req Doctor")]
		[ColumnEnum("ReqDoctor", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		ReqDoctor = 6,
		/// <summary>
		/// ReqDate : 
		/// </summary>
		[EnumTextValue("Req Date")]
		[ColumnEnum("ReqDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ReqDate = 7,
		/// <summary>
		/// ReqStatus : 
		/// </summary>
		[EnumTextValue("Req Status")]
		[ColumnEnum("ReqStatus", typeof(System.String), System.Data.DbType.String, false, false, true, 20)]
		ReqStatus = 8,
		/// <summary>
		/// Billable : 
		/// </summary>
		[EnumTextValue("Billable")]
		[ColumnEnum("Billable", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		Billable = 9,
		/// <summary>
		/// Sample : 
		/// </summary>
		[EnumTextValue("Sample")]
		[ColumnEnum("Sample", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Sample = 10
	}//End enum

	#endregion DoctorRequestColumn Enum

} // end namespace
