using System;
using System.ComponentModel;

namespace ePrescription.Entities
{
	/// <summary>
	///		The data structure representation of the 'ePrescription' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IEPrescription 
	{
		/// <summary>			
		/// PrescriptionID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ePrescription"</remarks>
		System.String PrescriptionId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalPrescriptionId { get; set; }
			
		
		
		/// <summary>
		/// TransactionID : 
		/// </summary>
		System.String  TransactionId  { get; set; }
		
		/// <summary>
		/// PatientCode : 
		/// </summary>
		System.String  PatientCode  { get; set; }
		
		/// <summary>
		/// FirstName : 
		/// </summary>
		System.String  FirstName  { get; set; }
		
		/// <summary>
		/// LastName : 
		/// </summary>
		System.String  LastName  { get; set; }
		
		/// <summary>
		/// DeliveryDate : 
		/// </summary>
		System.DateTime  DeliveryDate  { get; set; }
		
		/// <summary>
		/// CreateDate : 
		/// </summary>
		System.DateTime  CreateDate  { get; set; }
		
		/// <summary>
		/// Address : 
		/// </summary>
		System.String  Address  { get; set; }
		
		/// <summary>
		/// DateOfBirth : 
		/// </summary>
		System.DateTime?  DateOfBirth  { get; set; }
		
		/// <summary>
		/// Age : 
		/// </summary>
		System.String  Age  { get; set; }
		
		/// <summary>
		/// Weight : 
		/// </summary>
		System.String  Weight  { get; set; }
		
		/// <summary>
		/// Diagnosis : 
		/// </summary>
		System.String  Diagnosis  { get; set; }
		
		/// <summary>
		/// DiagnosisVN : 
		/// </summary>
		System.String  DiagnosisVn  { get; set; }
		
		/// <summary>
		/// DiagCode : 
		/// </summary>
		System.String  DiagCode  { get; set; }
		
		/// <summary>
		/// PrescribingDoctor : 
		/// </summary>
		System.String  PrescribingDoctor  { get; set; }
		
		/// <summary>
		/// Sex : 
		/// </summary>
		System.String  Sex  { get; set; }
		
		/// <summary>
		/// Remark : 
		/// </summary>
		System.String  Remark  { get; set; }
		
		/// <summary>
		/// IsComplete : 
		/// </summary>
		System.Boolean  IsComplete  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _ePrescriptionDetailPrescriptionId
		/// </summary>	
		TList<EPrescriptionDetail> EPrescriptionDetailCollection {  get;  set;}	

		#endregion Data Properties

	}
}


