using System;
using System.ComponentModel;

namespace ePrescription.Entities
{
	/// <summary>
	///		The data structure representation of the 'Route' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IRoute 
	{
		/// <summary>			
		/// RouteId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Route"</remarks>
		System.Int64 RouteId { get; set; }
				
		
		
		/// <summary>
		/// Route : 
		/// </summary>
		System.String  Route  { get; set; }
		
		/// <summary>
		/// RouteVN : 
		/// </summary>
		System.String  RouteVn  { get; set; }
		
		/// <summary>
		/// Description : 
		/// </summary>
		System.String  Description  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


