using System;
using System.ComponentModel;

namespace ePrescription.Entities
{
	/// <summary>
	///		The data structure representation of the 'Users' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IUsers 
	{
		/// <summary>			
		/// UserName : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Users"</remarks>
		System.String UserName { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalUserName { get; set; }
			
		
		
		/// <summary>
		/// Password : 
		/// </summary>
		System.String  Password  { get; set; }
		
		/// <summary>
		/// UserRole : 
		/// </summary>
		System.String  UserRole  { get; set; }
		
		/// <summary>
		/// FullName : 
		/// </summary>
		System.String  FullName  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// DisplayName : 
		/// </summary>
		System.String  DisplayName  { get; set; }
		
		/// <summary>
		/// Signature : 
		/// </summary>
		System.String  Signature  { get; set; }
		
		/// <summary>
		/// Location : 
		/// </summary>
		System.String  Location  { get; set; }
		
		/// <summary>
		/// IsDisabled : 
		/// </summary>
		System.Boolean  IsDisabled  { get; set; }
		
		/// <summary>
		/// Avatar : 
		/// </summary>
		System.String  Avatar  { get; set; }
		
		/// <summary>
		/// MobilePhone : 
		/// </summary>
		System.String  MobilePhone  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


