
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file PackageDetail.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using ePrescription.Entities.Validation;
#endregion

namespace ePrescription.Entities
{
	///<summary>
	/// An object representation of the 'PackageDetail' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class PackageDetailBase : EntityBase, IPackageDetail, IEntityId<PackageDetailKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private PackageDetailEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private PackageDetailEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private PackageDetailEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<PackageDetail> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PackageDetailEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PackageDetailEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="PackageDetailBase"/> instance.
		///</summary>
		public PackageDetailBase()
		{
			this.entityData = new PackageDetailEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="PackageDetailBase"/> instance.
		///</summary>
		///<param name="_packageId"></param>
		///<param name="_code"></param>
		///<param name="_description"></param>
		///<param name="_clinicPrice"></param>
		public PackageDetailBase(System.String _packageId, System.String _code, System.String _description, 
			System.Decimal? _clinicPrice)
		{
			this.entityData = new PackageDetailEntityData();
			this.backupData = null;

			this.PackageId = _packageId;
			this.Code = _code;
			this.Description = _description;
			this.ClinicPrice = _clinicPrice;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="PackageDetail"/> instance.
		///</summary>
		///<param name="_packageId"></param>
		///<param name="_code"></param>
		///<param name="_description"></param>
		///<param name="_clinicPrice"></param>
		public static PackageDetail CreatePackageDetail(System.String _packageId, System.String _code, System.String _description, 
			System.Decimal? _clinicPrice)
		{
			PackageDetail newPackageDetail = new PackageDetail();
			newPackageDetail.PackageId = _packageId;
			newPackageDetail.Code = _code;
			newPackageDetail.Description = _description;
			newPackageDetail.ClinicPrice = _clinicPrice;
			return newPackageDetail;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the PackageDetailId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "PackageDetailId is required")]




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 PackageDetailId
		{
			get
			{
				return this.entityData.PackageDetailId; 
			}
			
			set
			{
				if (this.entityData.PackageDetailId == value)
					return;
				
                OnPropertyChanging("PackageDetailId");                    
				OnColumnChanging(PackageDetailColumn.PackageDetailId, this.entityData.PackageDetailId);
				this.entityData.PackageDetailId = value;
				this.EntityId.PackageDetailId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PackageDetailColumn.PackageDetailId, this.entityData.PackageDetailId);
				OnPropertyChanged("PackageDetailId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PackageId property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		[Required(ErrorMessage = "PackageId is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 10)]
		public virtual System.String PackageId
		{
			get
			{
				return this.entityData.PackageId; 
			}
			
			set
			{
				if (this.entityData.PackageId == value)
					return;
				
                OnPropertyChanging("PackageId");                    
				OnColumnChanging(PackageDetailColumn.PackageId, this.entityData.PackageId);
				this.entityData.PackageId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PackageDetailColumn.PackageId, this.entityData.PackageId);
				OnPropertyChanged("PackageId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Code property. 
		///		
		/// </summary>
		/// <value>This type is char.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String Code
		{
			get
			{
				return this.entityData.Code; 
			}
			
			set
			{
				if (this.entityData.Code == value)
					return;
				
                OnPropertyChanging("Code");                    
				OnColumnChanging(PackageDetailColumn.Code, this.entityData.Code);
				this.entityData.Code = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PackageDetailColumn.Code, this.entityData.Code);
				OnPropertyChanged("Code");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 250)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
				
                OnPropertyChanging("Description");                    
				OnColumnChanging(PackageDetailColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PackageDetailColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ClinicPrice property. 
		///		
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? ClinicPrice
		{
			get
			{
				return this.entityData.ClinicPrice; 
			}
			
			set
			{
				if (this.entityData.ClinicPrice == value)
					return;
				
                OnPropertyChanging("ClinicPrice");                    
				OnColumnChanging(PackageDetailColumn.ClinicPrice, this.entityData.ClinicPrice);
				this.entityData.ClinicPrice = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PackageDetailColumn.ClinicPrice, this.entityData.ClinicPrice);
				OnPropertyChanged("ClinicPrice");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Package"/>.
		/// </summary>
		/// <value>The source Package for PackageId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Package PackageIdSource
      	{
            get { return entityData.PackageIdSource; }
            set { entityData.PackageIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("PackageId", "Package Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("PackageId", "Package Id", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Code", "Code", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Description", "Description", 250));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "PackageDetail"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"PackageDetailId", "PackageID", "Code", "Description", "ClinicPrice"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as PackageDetailEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (PackageDetail) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<PackageDetail>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as PackageDetail);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed PackageDetail Entity 
		///</summary>
		protected virtual PackageDetail Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			PackageDetail copy = new PackageDetail();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.PackageDetailId = this.PackageDetailId;
				copy.PackageId = this.PackageId;
				copy.Code = this.Code;
				copy.Description = this.Description;
				copy.ClinicPrice = this.ClinicPrice;
			
			if (this.PackageIdSource != null && existingCopies.Contains(this.PackageIdSource))
				copy.PackageIdSource = existingCopies[this.PackageIdSource] as Package;
			else
				copy.PackageIdSource = MakeCopyOf(this.PackageIdSource, existingCopies) as Package;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed PackageDetail Entity 
		///</summary>
		public virtual PackageDetail Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed PackageDetail Entity which is a deep copy of the current entity.
		///</summary>
		public virtual PackageDetail DeepCopy()
		{
			return EntityHelper.Clone<PackageDetail>(this as PackageDetail);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as PackageDetailEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new PackageDetailEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as PackageDetailEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(PackageDetailColumn column)
		{
			switch(column)
			{
					case PackageDetailColumn.PackageDetailId:
					return entityData.PackageDetailId != _originalData.PackageDetailId;
					case PackageDetailColumn.PackageId:
					return entityData.PackageId != _originalData.PackageId;
					case PackageDetailColumn.Code:
					return entityData.Code != _originalData.Code;
					case PackageDetailColumn.Description:
					return entityData.Description != _originalData.Description;
					case PackageDetailColumn.ClinicPrice:
					return entityData.ClinicPrice != _originalData.ClinicPrice;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< PackageDetailColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.PackageDetailId != _originalData.PackageDetailId;
			result = result || entityData.PackageId != _originalData.PackageId;
			result = result || entityData.Code != _originalData.Code;
			result = result || entityData.Description != _originalData.Description;
			result = result || entityData.ClinicPrice != _originalData.ClinicPrice;
			return result;
		}	
		
		///<summary>
		///  Returns a PackageDetail Entity with the original data.
		///</summary>
		public PackageDetail GetOriginalEntity()
		{
			if (_originalData != null)
				return CreatePackageDetail(
				_originalData.PackageId,
				_originalData.Code,
				_originalData.Description,
				_originalData.ClinicPrice
				);
				
			return (PackageDetail)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="PackageDetailBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is PackageDetailBase)
				return ValueEquals(this, (PackageDetailBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="PackageDetailBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.PackageDetailId.GetHashCode() ^ 
					this.PackageId.GetHashCode() ^ 
					((this.Code == null) ? string.Empty : this.Code.ToString()).GetHashCode() ^ 
					((this.Description == null) ? string.Empty : this.Description.ToString()).GetHashCode() ^ 
					((this.ClinicPrice == null) ? string.Empty : this.ClinicPrice.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="PackageDetailBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(PackageDetailBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="PackageDetailBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="PackageDetailBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="PackageDetailBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(PackageDetailBase Object1, PackageDetailBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.PackageDetailId != Object2.PackageDetailId)
				equal = false;
			if (Object1.PackageId != Object2.PackageId)
				equal = false;
			if ( Object1.Code != null && Object2.Code != null )
			{
				if (Object1.Code != Object2.Code)
					equal = false;
			}
			else if (Object1.Code == null ^ Object2.Code == null )
			{
				equal = false;
			}
			if ( Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object2.Description == null )
			{
				equal = false;
			}
			if ( Object1.ClinicPrice != null && Object2.ClinicPrice != null )
			{
				if (Object1.ClinicPrice != Object2.ClinicPrice)
					equal = false;
			}
			else if (Object1.ClinicPrice == null ^ Object2.ClinicPrice == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((PackageDetailBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static PackageDetailComparer GetComparer()
        {
            return new PackageDetailComparer();
        }
        */

        // Comparer delegates back to PackageDetail
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(PackageDetail rhs, PackageDetailColumn which)
        {
            switch (which)
            {
            	
            	
            	case PackageDetailColumn.PackageDetailId:
            		return this.PackageDetailId.CompareTo(rhs.PackageDetailId);
            		
            		                 
            	
            	
            	case PackageDetailColumn.PackageId:
            		return this.PackageId.CompareTo(rhs.PackageId);
            		
            		                 
            	
            	
            	case PackageDetailColumn.Code:
            		return this.Code.CompareTo(rhs.Code);
            		
            		                 
            	
            	
            	case PackageDetailColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            	
            	
            	case PackageDetailColumn.ClinicPrice:
            		return this.ClinicPrice.Value.CompareTo(rhs.ClinicPrice.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<PackageDetailKey> Members
		
		// member variable for the EntityId property
		private PackageDetailKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual PackageDetailKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new PackageDetailKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("PackageDetail")
					.Append("|").Append( this.PackageDetailId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- PackageDetailId: {0}{5}- PackageId: {1}{5}- Code: {2}{5}- Description: {3}{5}- ClinicPrice: {4}{5}{7}", 
				this.PackageDetailId,
				this.PackageId,
				(this.Code == null) ? string.Empty : this.Code.ToString(),
				(this.Description == null) ? string.Empty : this.Description.ToString(),
				(this.ClinicPrice == null) ? string.Empty : this.ClinicPrice.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'PackageDetail' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class PackageDetailEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// PackageDetailId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "PackageDetail"</remarks>
		public System.Int32 PackageDetailId;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// PackageID : 
		/// </summary>
		public System.String PackageId = string.Empty;
		
		/// <summary>
		/// Code : 
		/// </summary>
		public System.String Code = null;
		
		/// <summary>
		/// Description : 
		/// </summary>
		public System.String Description = null;
		
		/// <summary>
		/// ClinicPrice : 
		/// </summary>
		public System.Decimal? ClinicPrice = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Package _packageIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Package"/>.
		/// </summary>
		/// <value>The source Package for PackageId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Package PackageIdSource
      	{
            get { return this._packageIdSource; }
            set { this._packageIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			PackageDetailEntityData _tmp = new PackageDetailEntityData();
						
			_tmp.PackageDetailId = this.PackageDetailId;
			
			_tmp.PackageId = this.PackageId;
			_tmp.Code = this.Code;
			_tmp.Description = this.Description;
			_tmp.ClinicPrice = this.ClinicPrice;
			
			#region Source Parent Composite Entities
			if (this.PackageIdSource != null)
				_tmp.PackageIdSource = MakeCopyOf(this.PackageIdSource) as Package;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			PackageDetailEntityData _tmp = new PackageDetailEntityData();
						
			_tmp.PackageDetailId = this.PackageDetailId;
			
			_tmp.PackageId = this.PackageId;
			_tmp.Code = this.Code;
			_tmp.Description = this.Description;
			_tmp.ClinicPrice = this.ClinicPrice;
			
			#region Source Parent Composite Entities
			if (this.PackageIdSource != null && existingCopies.Contains(this.PackageIdSource))
				_tmp.PackageIdSource = existingCopies[this.PackageIdSource] as Package;
			else
				_tmp.PackageIdSource = MakeCopyOf(this.PackageIdSource, existingCopies) as Package;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PackageDetailColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(PackageDetailColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PackageDetailColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(PackageDetailColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PackageDetailColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(PackageDetailColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				PackageDetailEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new PackageDetailEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PackageDetailColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(PackageDetailColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				PackageDetailEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new PackageDetailEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region PackageDetailEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="PackageDetail"/> object.
	/// </remarks>
	public class PackageDetailEventArgs : System.EventArgs
	{
		private PackageDetailColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the PackageDetailEventArgs class.
		///</summary>
		public PackageDetailEventArgs(PackageDetailColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the PackageDetailEventArgs class.
		///</summary>
		public PackageDetailEventArgs(PackageDetailColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The PackageDetailColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="PackageDetailColumn" />
		public PackageDetailColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all PackageDetail related events.
	///</summary>
	public delegate void PackageDetailEventHandler(object sender, PackageDetailEventArgs e);
	
	#region PackageDetailComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class PackageDetailComparer : System.Collections.Generic.IComparer<PackageDetail>
	{
		PackageDetailColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:PackageDetailComparer"/> class.
        /// </summary>
		public PackageDetailComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PackageDetailComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public PackageDetailComparer(PackageDetailColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="PackageDetail"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="PackageDetail"/> to compare.</param>
        /// <param name="b">The second <c>PackageDetail</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(PackageDetail a, PackageDetail b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(PackageDetail entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(PackageDetail a, PackageDetail b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public PackageDetailColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region PackageDetailKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="PackageDetail"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class PackageDetailKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the PackageDetailKey class.
		/// </summary>
		public PackageDetailKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the PackageDetailKey class.
		/// </summary>
		public PackageDetailKey(PackageDetailBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.PackageDetailId = entity.PackageDetailId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the PackageDetailKey class.
		/// </summary>
		public PackageDetailKey(System.Int32 _packageDetailId)
		{
			#region Init Properties

			this.PackageDetailId = _packageDetailId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private PackageDetailBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public PackageDetailBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the PackageDetailId property
		private System.Int32 _packageDetailId;
		
		/// <summary>
		/// Gets or sets the PackageDetailId property.
		/// </summary>
		public System.Int32 PackageDetailId
		{
			get { return _packageDetailId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.PackageDetailId = value;
				
				_packageDetailId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				PackageDetailId = ( values["PackageDetailId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["PackageDetailId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("PackageDetailId", PackageDetailId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("PackageDetailId: {0}{1}",
								PackageDetailId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region PackageDetailColumn Enum
	
	/// <summary>
	/// Enumerate the PackageDetail columns.
	/// </summary>
	[Serializable]
	public enum PackageDetailColumn : int
	{
		/// <summary>
		/// PackageDetailId : 
		/// </summary>
		[EnumTextValue("Package Detail Id")]
		[ColumnEnum("PackageDetailId", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		PackageDetailId = 1,
		/// <summary>
		/// PackageId : 
		/// </summary>
		[EnumTextValue("Package Id")]
		[ColumnEnum("PackageID", typeof(System.String), System.Data.DbType.String, false, false, false, 10)]
		PackageId = 2,
		/// <summary>
		/// Code : 
		/// </summary>
		[EnumTextValue("Code")]
		[ColumnEnum("Code", typeof(System.String), System.Data.DbType.AnsiStringFixedLength, false, false, true, 10)]
		Code = 3,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("Description", typeof(System.String), System.Data.DbType.String, false, false, true, 250)]
		Description = 4,
		/// <summary>
		/// ClinicPrice : 
		/// </summary>
		[EnumTextValue("Clinic Price")]
		[ColumnEnum("ClinicPrice", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		ClinicPrice = 5
	}//End enum

	#endregion PackageDetailColumn Enum

} // end namespace
